# render.yaml - Place in project root

services:
  # Backend API Service
  - type: web
    name: watermark-backend-a4l8
    runtime: docker
    repo: https://github.com/kyroX-D/Watermark-Ai
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: watermark-ai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://watermark-ai-frontend.onrender.com"]'
      - key: FRONTEND_URL
        value: https://watermark-ai-frontend.onrender.com
      - key: API_URL
        value: https://watermark-backend-a4l8.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: STRIPE_PRICE_ELITE
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OXAPAY_MERCHANT_ID
        sync: false
      - key: OXAPAY_API_KEY
        sync: false
      - key: OXAPAY_WEBHOOK_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: watermark-ai-frontend
    runtime: static
    repo: https://github.com/kyroX-D/Watermark-Ai
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_URL
        value: https://watermark-backend-a4l8.onrender.com
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: no-cache

databases:
  - name: watermark-ai-db
    plan: starter
    databaseName: watermark_ai
    user: watermark_user