# render.yaml
services:
  - type: web
    name: watermark-ai-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: |
      cd backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: watermark-ai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '["https://watermark-ai-frontend.onrender.com"]'
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: STRIPE_PRICE_ELITE
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OXAPAY_MERCHANT_ID
        sync: false
      - key: OXAPAY_API_KEY
        sync: false
      - key: OXAPAY_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://watermark-ai-frontend.onrender.com
      - key: API_URL
        value: https://watermark-ai-backend.onrender.com

databases:
  - name: watermark-ai-db
    databaseName: watermark_ai
    user: watermark_user
    region: oregon
    plan: starter